[colors]
[colors.normal]
black = "#475258"
blue = "#7fbbb3" 
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.cursor]
cursor = "0xFFFCF0"
text = "0xFFFCF0"

[colors.bright]
black = '#475258'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'

[colors.primary]
background = "0x100F0F"
bright_foreground = "0xFFFCF0"
dim_foreground = "0xFFFCF0"
foreground = "0xFFFCF0"

[cursor]
style.shape = "Underline"
